import React from 'react';

type StyleObject = {
  [key: string]: React.CSSProperties;
};

// Centralized style object for all inline styles
export const styles: StyleObject = {
	card: {
		borderWidth: "2px",
		borderStyle: "solid",
		borderColor: "#bfdbfe",
		borderRadius: "8px",
		boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
		background: "white",
		fontFamily: "Inter, sans-serif",
	},
	cardHeader: {
		background: "linear-gradient(to right, #eff6ff, #eef2ff)",
		borderBottom: "1px solid #e5e7eb",
		padding: "1.5rem",
	},
	cardTitle: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		color: "#1e3a8a",
		fontSize: "1.35rem",
		fontWeight: 600,
		margin: 0,
	},
	cardContent: {
		padding: "1.5rem",
		display: "flex",
		flexDirection: "column",
		gap: "1.5rem",
	},
	btn: {
		padding: "0.5rem 1rem",
		borderRadius: "6px",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: "#d1d5db",
		background: "white",
		cursor: "pointer",
		fontSize: "0.95rem",
		fontWeight: 500,
		transition: "all 0.2s",
		display: "inline-flex",
		alignItems: "center",
		justifyContent: "center",
		gap: "0.5rem",
		color: "#374151",
		textDecoration: "none",
	},
	btnHover: { background: "#f9fafb" },
	btnPrimary: {
		background: "#2563eb",
		color: "white",
		borderColor: "#2563eb",
	},
	btnPrimaryHover: { background: "#1d4ed8" },
	btnGradient: {
		background: "linear-gradient(to right, #a855f7, #ec4899)",
		color: "white",
		borderStyle: "none",
	},
	btnGradientHover: {
		background: "linear-gradient(to right, #9333ea, #db2777)",
	},
	btnOutline: { background: "transparent", color: "#6b7280" },
	btnOutlineHover: { color: "#374151", background: "#f3f4f6" },
	btnGhost: {
		background: "transparent",
		borderStyle: "none",
		color: "#374151",
	},
	btnGhostHover: { background: "#f3f4f6" },
	btnSm: { padding: "0.25rem 0.75rem", fontSize: "0.85rem" },
	btnLg: { padding: "0.75rem 1.5rem", fontSize: "1.1rem" },
	input: {
		padding: "0.5rem 0.75rem",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: "#d1d5db",
		borderRadius: "6px",
		fontSize: "0.95rem",
		width: "100%",
		boxSizing: "border-box",
		transition: "all 0.2s",
	},
	inputFocus: {
		outline: "none",
		borderColor: "#3b82f6",
		boxShadow: "0 0 0 3px rgba(59, 130, 246, 0.1)",
	},
	label: {
		fontSize: "0.95rem",
		fontWeight: 500,
		color: "#374151",
		marginBottom: "0.5rem",
		display: "block",
	},
	spaceY2: { display: "flex", flexDirection: "column", gap: "0.5rem" },
	badge: {
		display: "inline-flex",
		alignItems: "center",
		padding: "0.25rem 0.75rem",
		borderRadius: "9999px",
		fontSize: "0.85rem",
		fontWeight: 500,
		background: "#dbeafe",
		color: "#1e40af",
		gap: "0.25rem",
	},
	dropdown: { position: "relative", width: "100%" },
	dropdownContent: {
		position: "absolute",
		top: "calc(100% + 4px)",
		left: 0,
		right: 0,
		background: "white",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: "#d1d5db",
		borderRadius: "6px",
		boxShadow: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
		zIndex: 10,
		maxHeight: "16rem",
		overflowY: "auto",
		padding: "0.5rem",
		boxSizing: "border-box",
	},
	checkboxItem: {
		display: "flex",
		alignItems: "flex-start",
		gap: "0.75rem",
		padding: "0.5rem",
		borderRadius: "4px",
		cursor: "pointer",
	},
	checkboxItemHover: { backgroundColor: "#f3f4f6" },
	checkbox: {
		width: "1rem",
		height: "1rem",
		marginTop: "0.2rem",
		flexShrink: 0,
	},
	tagGridItem: {
		padding: "0.5rem",
		borderRadius: "6px",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: "#d1d5db",
		cursor: "pointer",
		transition: "all 0.2s",
		background: "white",
	},
	tagGridItemHover: { borderColor: "#9ca3af" },
	tagGridItemSelected: {
		background: "#dbeafe",
		borderColor: "#93c5fd",
		color: "#1e40af",
	},
	problemIndexGrid: {
		display: "grid",
		gridTemplateColumns: "repeat(auto-fill, minmax(40px, 1fr))",
		gap: "0.5rem",
	},
	problemIndexItem: {
		padding: "0.5rem",
		borderRadius: "6px",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: "#d1d5db",
		cursor: "pointer",
		transition: "all 0.2s",
		textAlign: "center",
		background: "white",
	},
	problemIndexItemHover: { borderColor: "#9ca3af" },
	problemIndexItemSelected: {
		background: "#dbeafe",
		borderColor: "#93c5fd",
		color: "#1e40af",
	},
	separator: { height: "1px", background: "#e5e7eb", margin: "1rem 0" },
	filterSummary: {
		fontSize: "0.85rem",
		color: "#6b7280",
		background: "#f9fafb",
		padding: "0.75rem",
		borderRadius: "6px",
		wordBreak: "break-word",
	},
	scrollArea: {
		maxHeight: "16rem",
		overflowY: "auto",
		padding: "0.5rem",
		borderWidth: "1px",
		borderStyle: "solid",
		borderColor: "#d1d5db",
		borderRadius: "6px",
		background: "#f9fafb",
	},
	icon: {
		width: "1.25rem",
		height: "1.25rem",
		strokeWidth: 2,
		flexShrink: 0,
	},
	iconSm: { width: "0.75rem", height: "0.75rem" },
	borderT: {
		borderTop: "1px solid #e5e7eb",
		paddingTop: "1.5rem",
		marginTop: "1.5rem",
	},
	radioGroup: {
		display: "flex",
		gap: "1rem",
		alignItems: "center",
		height: "100%",
	},
	radioItem: {
		display: "flex",
		alignItems: "center",
gap: "0.5rem",
		cursor: "pointer",
	},
	radio: { width: "1rem", height: "1rem" },
};
