export interface Problem {
  name: string;
  tags: string[];
  index: string;
  cfRating: number | null;
  contestId: number;
  clistRating: number | null;
  problemDate: string; // ISO date string (e.g., "2021-02-23T00:00:00")
  totalAccepted: number;
  inContestAccepted: number;
  inContestAttempts: number;
  contestRegistrants: number;
}
export const ProblemService = {
  getProblemsData(): Problem[] {
    return [
      {
        "name": "Genius's Gambit",
        "tags": ["bitmasks", "constructive algorithms", "greedy", "math"],
        "index": "D",
        "cfRating": 1900,
        "contestId": 1492,
        "clistRating": 1965,
        "problemDate": "2021-02-23T00:00:00",
        "totalAccepted": 6310,
        "inContestAccepted": 876,
        "inContestAttempts": 2840,
        "contestRegistrants": 9512
      },
      {
        "name": "Pictures with Kittens (easy version)",
        "tags": ["dp"],
        "index": "F1",
        "cfRating": 1900,
        "contestId": 1077,
        "clistRating": 2088,
        "problemDate": "2018-11-16T00:00:00",
        "totalAccepted": 4817,
        "inContestAccepted": 298,
        "inContestAttempts": 496,
        "contestRegistrants": 5880
      },
      {
        "name": "Edge Deletion",
        "tags": ["graphs", "greedy", "shortest paths"],
        "index": "D",
        "cfRating": 1800,
        "contestId": 1076,
        "clistRating": 2008,
        "problemDate": "2018-11-12T00:00:00",
        "totalAccepted": 5557,
        "inContestAccepted": 494,
        "inContestAttempts": 1421,
        "contestRegistrants": 4823
      },
      {
        "name": "Jellyfish Nightmare",
        "tags": [],
        "index": "G",
        "cfRating": 3500,
        "contestId": 1055,
        "clistRating": 3718,
        "problemDate": "2018-11-10T00:00:00",
        "totalAccepted": 93,
        "inContestAccepted": 1,
        "inContestAttempts": 10,
        "contestRegistrants": 3292
      },
      {
        "name": "Smallest Word",
        "tags": ["constructive algorithms", "greedy", "implementation"],
        "index": "C",
        "cfRating": 1500,
        "contestId": 1043,
        "clistRating": 1475,
        "problemDate": "2018-10-28T00:00:00",
        "totalAccepted": 7067,
        "inContestAccepted": 2351,
        "inContestAttempts": 2997,
        "contestRegistrants": 4567
      },
      {
        "name": "Up and Down the Tree",
        "tags": ["dfs and similar", "dp", "trees"],
        "index": "F",
        "cfRating": 2500,
        "contestId": 1065,
        "clistRating": 2599,
        "problemDate": "2018-10-11T00:00:00",
        "totalAccepted": 1252,
        "inContestAccepted": 50,
        "inContestAttempts": 148,
        "contestRegistrants": 5410
      },
      {
        "name": "Rectangles",
        "tags": ["geometry", "implementation", "sortings"],
        "index": "C",
        "cfRating": 1600,
        "contestId": 1028,
        "clistRating": 1764,
        "problemDate": "2018-08-27T00:00:00",
        "totalAccepted": 4843,
        "inContestAccepted": 1274,
        "inContestAttempts": 2542,
        "contestRegistrants": 4382
      },
      {
        "name": "Minimum Value Rectangle",
        "tags": ["greedy"],
        "index": "C",
        "cfRating": 1600,
        "contestId": 1027,
        "clistRating": 1635,
        "problemDate": "2018-08-18T00:00:00",
        "totalAccepted": 7028,
        "inContestAccepted": 1849,
        "inContestAttempts": 3624,
        "contestRegistrants": 5447
      },
      {
        "name": "Walking Between Houses",
        "tags": ["constructive algorithms", "greedy"],
        "index": "D",
        "cfRating": 1600,
        "contestId": 1015,
        "clistRating": 1679,
        "problemDate": "2018-07-31T00:00:00",
        "totalAccepted": 8608,
        "inContestAccepted": 1093,
        "inContestAttempts": 2225,
        "contestRegistrants": 5200
      },
      {
        "name": "Add or XOR",
        "tags": ["bitmasks", "greedy", "math"],
        "index": "A",
        "cfRating": null,
        "contestId": 2119,
        "clistRating": 651,
        "problemDate": "2025-07-05T00:00:00",
        "totalAccepted": 18958,
        "inContestAccepted": 14069,
        "inContestAttempts": 15948,
        "contestRegistrants": 16323
      },
      {
        "name": "Line Segments",
        "tags": ["geometry", "greedy", "math"],
        "index": "B",
        "cfRating": null,
        "contestId": 2119,
        "clistRating": 1168,
        "problemDate": "2025-07-05T00:00:00",
        "totalAccepted": 12689,
        "inContestAccepted": 8381,
        "inContestAttempts": 12751,
        "contestRegistrants": 16323
      },
      {
        "name": "A Good Problem",
        "tags": ["bitmasks", "constructive algorithms", "math"],
        "index": "C",
        "cfRating": null,
        "contestId": 2119,
        "clistRating": 1250,
        "problemDate": "2025-07-05T00:00:00",
        "totalAccepted": 10913,
        "inContestAccepted": 7000,
        "inContestAttempts": 8799,
        "contestRegistrants": 16323
      },
      {
        "name": "Token Removing",
        "tags": ["combinatorics", "dp", "math"],
        "index": "D",
        "cfRating": null,
        "contestId": 2119,
        "clistRating": 2074,
        "problemDate": "2025-07-05T00:00:00",
        "totalAccepted": 1936,
        "inContestAccepted": 763,
        "inContestAttempts": 1228,
        "contestRegistrants": 16323
      },
      {
        "name": "And Constraint",
        "tags": ["bitmasks", "dp", "greedy"],
        "index": "E",
        "cfRating": null,
        "contestId": 2119,
        "clistRating": 2757,
        "problemDate": "2025-07-05T00:00:00",
        "totalAccepted": 303,
        "inContestAccepted": 57,
        "inContestAttempts": 272,
        "contestRegistrants": 16323
      },
      {
        "name": "Volcanic Eruptions",
        "tags": ["dfs and similar", "dp", "greedy", "shortest paths", "trees"],
        "index": "F",
        "cfRating": null,
        "contestId": 2119,
        "clistRating": 3405,
        "problemDate": "2025-07-05T00:00:00",
        "totalAccepted": 64,
        "inContestAccepted": 5,
        "inContestAttempts": 187,
        "contestRegistrants": 16323
      },
      {
        "name": "Blackboard Game",
        "tags": ["math"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2123,
        "clistRating": 513,
        "problemDate": "2025-07-01T00:00:00",
        "totalAccepted": 31535,
        "inContestAccepted": 23012,
        "inContestAttempts": 25425,
        "contestRegistrants": 26516
      },
      {
        "name": "Tournament",
        "tags": ["greedy"],
        "index": "B",
        "cfRating": 800,
        "contestId": 2123,
        "clistRating": 768,
        "problemDate": "2025-07-01T00:00:00",
        "totalAccepted": 26639,
        "inContestAccepted": 18421,
        "inContestAttempts": 23091,
        "contestRegistrants": 26516
      },
      {
        "name": "Prefix Min and Suffix Max",
        "tags": ["brute force", "data structures"],
        "index": "C",
        "cfRating": 1000,
        "contestId": 2123,
        "clistRating": 905,
        "problemDate": "2025-07-01T00:00:00",
        "totalAccepted": 22780,
        "inContestAccepted": 15638,
        "inContestAttempts": 18882,
        "contestRegistrants": 26516
      },
      {
        "name": "Binary String Battle",
        "tags": ["constructive algorithms", "games", "greedy"],
        "index": "D",
        "cfRating": 1200,
        "contestId": 2123,
        "clistRating": 1259,
        "problemDate": "2025-07-01T00:00:00",
        "totalAccepted": 15644,
        "inContestAccepted": 8492,
        "inContestAttempts": 12180,
        "contestRegistrants": 26516
      },
      {
        "name": "MEX Count",
        "tags": [
          "binary search",
          "data structures",
          "greedy",
          "sortings",
          "two pointers"
        ],
        "index": "E",
        "cfRating": 1400,
        "contestId": 2123,
        "clistRating": 1470,
        "problemDate": "2025-07-01T00:00:00",
        "totalAccepted": 10109,
        "inContestAccepted": 4998,
        "inContestAttempts": 6408,
        "contestRegistrants": 26516
      },
      {
        "name": "Minimize Fixed Points",
        "tags": ["constructive algorithms", "number theory"],
        "index": "F",
        "cfRating": 1700,
        "contestId": 2123,
        "clistRating": 1702,
        "problemDate": "2025-07-01T00:00:00",
        "totalAccepted": 6510,
        "inContestAccepted": 2472,
        "inContestAttempts": 4027,
        "contestRegistrants": 26516
      },
      {
        "name": "Modular Sorting",
        "tags": [
          "brute force",
          "data structures",
          "greedy",
          "math",
          "number theory",
          "sortings"
        ],
        "index": "G",
        "cfRating": 2100,
        "contestId": 2123,
        "clistRating": 2203,
        "problemDate": "2025-07-01T00:00:00",
        "totalAccepted": 1819,
        "inContestAccepted": 423,
        "inContestAttempts": 1131,
        "contestRegistrants": 26516
      },
      {
        "name": "Square of Rectangles",
        "tags": ["geometry", "math"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2120,
        "clistRating": 763,
        "problemDate": "2025-06-21T00:00:00",
        "totalAccepted": 16378,
        "inContestAccepted": 11009,
        "inContestAttempts": 13224,
        "contestRegistrants": 13533
      },
      {
        "name": "Square Pool",
        "tags": ["geometry"],
        "index": "B",
        "cfRating": 1000,
        "contestId": 2120,
        "clistRating": 910,
        "problemDate": "2025-06-21T00:00:00",
        "totalAccepted": 13834,
        "inContestAccepted": 9595,
        "inContestAttempts": 10359,
        "contestRegistrants": 13533
      },
      {
        "name": "Divine Tree",
        "tags": ["constructive algorithms", "greedy", "math", "sortings", "trees"],
        "index": "C",
        "cfRating": 1400,
        "contestId": 2120,
        "clistRating": 1345,
        "problemDate": "2025-06-21T00:00:00",
        "totalAccepted": 8960,
        "inContestAccepted": 5066,
        "inContestAttempts": 7289,
        "contestRegistrants": 13533
      },
      {
        "name": "Matrix game",
        "tags": ["combinatorics", "math"],
        "index": "D",
        "cfRating": 1800,
        "contestId": 2120,
        "clistRating": 1751,
        "problemDate": "2025-06-21T00:00:00",
        "totalAccepted": 4218,
        "inContestAccepted": 1997,
        "inContestAttempts": 2767,
        "contestRegistrants": 13533
      },
      {
        "name": "Lanes of Cars",
        "tags": ["binary search", "dp", "ternary search"],
        "index": "E",
        "cfRating": 2300,
        "contestId": 2120,
        "clistRating": 2192,
        "problemDate": "2025-06-21T00:00:00",
        "totalAccepted": 1206,
        "inContestAccepted": 463,
        "inContestAttempts": 1231,
        "contestRegistrants": 13533
      },
      {
        "name": "Superb Graphs",
        "tags": ["2-sat", "graphs"],
        "index": "F",
        "cfRating": 2600,
        "contestId": 2120,
        "clistRating": 2661,
        "problemDate": "2025-06-21T00:00:00",
        "totalAccepted": 220,
        "inContestAccepted": 68,
        "inContestAttempts": 306,
        "contestRegistrants": 13533
      },
      {
        "name": "Eulerian Line Graph",
        "tags": ["graphs", "greedy", "math"],
        "index": "G",
        "cfRating": 3000,
        "contestId": 2120,
        "clistRating": 3455,
        "problemDate": "2025-06-21T00:00:00",
        "totalAccepted": 66,
        "inContestAccepted": 2,
        "inContestAttempts": 177,
        "contestRegistrants": 13533
      },
      {
        "name": "Letter Home",
        "tags": ["brute force", "math"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2121,
        "clistRating": 389,
        "problemDate": "2025-06-17T00:00:00",
        "totalAccepted": 31504,
        "inContestAccepted": 22893,
        "inContestAttempts": 24151,
        "contestRegistrants": 24952
      },
      {
        "name": "Above the Clouds",
        "tags": ["constructive algorithms", "greedy", "strings"],
        "index": "B",
        "cfRating": 800,
        "contestId": 2121,
        "clistRating": 666,
        "problemDate": "2025-06-17T00:00:00",
        "totalAccepted": 26819,
        "inContestAccepted": 19453,
        "inContestAttempts": 21167,
        "contestRegistrants": 24952
      },
      {
        "name": "Those Who Are With Us",
        "tags": ["greedy", "greedy", "implementation"],
        "index": "C",
        "cfRating": 1200,
        "contestId": 2121,
        "clistRating": 1217,
        "problemDate": "2025-06-17T00:00:00",
        "totalAccepted": 16245,
        "inContestAccepted": 9120,
        "inContestAttempts": 14848,
        "contestRegistrants": 24952
      },
      {
        "name": "1709",
        "tags": ["implementation", "sortings"],
        "index": "D",
        "cfRating": 1300,
        "contestId": 2121,
        "clistRating": 1318,
        "problemDate": "2025-06-17T00:00:00",
        "totalAccepted": 13457,
        "inContestAccepted": 7362,
        "inContestAttempts": 9720,
        "contestRegistrants": 24952
      },
      {
        "name": "Sponsor of Your Problems",
        "tags": ["dp", "greedy", "implementation", "strings"],
        "index": "E",
        "cfRating": 1500,
        "contestId": 2121,
        "clistRating": 1481,
        "problemDate": "2025-06-17T00:00:00",
        "totalAccepted": 9918,
        "inContestAccepted": 4855,
        "inContestAttempts": 6150,
        "contestRegistrants": 24952
      },
      {
        "name": "Yamakasi",
        "tags": [
          "binary search",
          "brute force",
          "data structures",
          "greedy",
          "two pointers"
        ],
        "index": "F",
        "cfRating": 1800,
        "contestId": 2121,
        "clistRating": 1820,
        "problemDate": "2025-06-17T00:00:00",
        "totalAccepted": 5271,
        "inContestAccepted": 1546,
        "inContestAttempts": 3301,
        "contestRegistrants": 24952
      },
      {
        "name": "Gangsta",
        "tags": ["data structures", "divide and conquer", "math", "sortings"],
        "index": "G",
        "cfRating": 1900,
        "contestId": 2121,
        "clistRating": 1868,
        "problemDate": "2025-06-17T00:00:00",
        "totalAccepted": 3193,
        "inContestAccepted": 1404,
        "inContestAttempts": 1881,
        "contestRegistrants": 24952
      },
      {
        "name": "Ice Baby",
        "tags": [
          "binary search",
          "brute force",
          "data structures",
          "dp",
          "implementation",
          "sortings"
        ],
        "index": "H",
        "cfRating": 2300,
        "contestId": 2121,
        "clistRating": 2348,
        "problemDate": "2025-06-17T00:00:00",
        "totalAccepted": 1280,
        "inContestAccepted": 223,
        "inContestAttempts": 659,
        "contestRegistrants": 24952
      },
      {
        "name": "Make It Permutation",
        "tags": ["constructive algorithms"],
        "index": "B",
        "cfRating": 1200,
        "contestId": 2118,
        "clistRating": 1199,
        "problemDate": "2025-06-12T00:00:00",
        "totalAccepted": 16291,
        "inContestAccepted": 8789,
        "inContestAttempts": 12514,
        "contestRegistrants": 18846
      },
      {
        "name": "Equal Subsequences",
        "tags": ["constructive algorithms", "greedy"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2118,
        "clistRating": 526,
        "problemDate": "2025-06-12T00:00:00",
        "totalAccepted": 24970,
        "inContestAccepted": 17019,
        "inContestAttempts": 18538,
        "contestRegistrants": 18846
      },
      {
        "name": "Make It Beautiful",
        "tags": ["bitmasks", "data structures", "greedy", "math"],
        "index": "C",
        "cfRating": 1300,
        "contestId": 2118,
        "clistRating": 1236,
        "problemDate": "2025-06-12T00:00:00",
        "totalAccepted": 14675,
        "inContestAccepted": 8077,
        "inContestAttempts": 10216,
        "contestRegistrants": 18846
      },
      {
        "name": "Shifts and Swaps",
        "tags": ["data structures", "graphs", "hashing", "trees"],
        "index": "F",
        "cfRating": 3100,
        "contestId": 2118,
        "clistRating": 3166,
        "problemDate": "2025-06-12T00:00:00",
        "totalAccepted": 168,
        "inContestAccepted": 13,
        "inContestAttempts": 146,
        "contestRegistrants": 18846
      },
      {
        "name": "Cool Partition",
        "tags": ["data structures", "greedy"],
        "index": "C",
        "cfRating": 1200,
        "contestId": 2117,
        "clistRating": 1240,
        "problemDate": "2025-06-08T00:00:00",
        "totalAccepted": 16578,
        "inContestAccepted": 8073,
        "inContestAttempts": 13753,
        "contestRegistrants": 23216
      },
      {
        "name": "Lost Soul",
        "tags": ["brute force", "greedy"],
        "index": "E",
        "cfRating": 1600,
        "contestId": 2117,
        "clistRating": 1606,
        "problemDate": "2025-06-08T00:00:00",
        "totalAccepted": 8916,
        "inContestAccepted": 3047,
        "inContestAttempts": 4474,
        "contestRegistrants": 23216
      },
      {
        "name": "Wildflower",
        "tags": ["combinatorics", "dfs and similar", "trees"],
        "index": "F",
        "cfRating": 1800,
        "contestId": 2117,
        "clistRating": 1935,
        "problemDate": "2025-06-08T00:00:00",
        "totalAccepted": 4294,
        "inContestAccepted": 1046,
        "inContestAttempts": 1663,
        "contestRegistrants": 23216
      },
      {
        "name": "Omg Graph",
        "tags": [
          "brute force",
          "dsu",
          "graphs",
          "greedy",
          "shortest paths",
          "sortings"
        ],
        "index": "G",
        "cfRating": 1900,
        "contestId": 2117,
        "clistRating": 2038,
        "problemDate": "2025-06-08T00:00:00",
        "totalAccepted": 3348,
        "inContestAccepted": 722,
        "inContestAttempts": 1516,
        "contestRegistrants": 23216
      },
      {
        "name": "Incessant Rain",
        "tags": ["data structures", "divide and conquer", "sortings"],
        "index": "H",
        "cfRating": 2500,
        "contestId": 2117,
        "clistRating": 2691,
        "problemDate": "2025-06-08T00:00:00",
        "totalAccepted": 561,
        "inContestAccepted": 55,
        "inContestAttempts": 417,
        "contestRegistrants": 23216
      },
      {
        "name": "Gellyfish and Tricolor Pansy",
        "tags": ["games", "greedy"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2116,
        "clistRating": 713,
        "problemDate": "2025-05-31T00:00:00",
        "totalAccepted": 23397,
        "inContestAccepted": 15173,
        "inContestAttempts": 18479,
        "contestRegistrants": 18762
      },
      {
        "name": "Gellyfish and Baby's Breath",
        "tags": ["greedy", "math", "sortings"],
        "index": "B",
        "cfRating": 1300,
        "contestId": 2116,
        "clistRating": 1234,
        "problemDate": "2025-05-31T00:00:00",
        "totalAccepted": 14178,
        "inContestAccepted": 7463,
        "inContestAttempts": 12992,
        "contestRegistrants": 18762
      },
      {
        "name": "Gellyfish and Mayflower",
        "tags": ["dp", "graphs"],
        "index": "E",
        "cfRating": 3500,
        "contestId": 2115,
        "clistRating": 3584,
        "problemDate": "2025-05-31T00:00:00",
        "totalAccepted": 129,
        "inContestAccepted": 8,
        "inContestAttempts": 24,
        "contestRegistrants": 957
      },
      {
        "name": "Gellyfish and Lycoris Radiata (Easy Version)",
        "tags": ["data structures"],
        "index": "F1",
        "cfRating": 3500,
        "contestId": 2115,
        "clistRating": 4599,
        "problemDate": "2025-05-31T00:00:00",
        "totalAccepted": 41,
        "inContestAccepted": 0,
        "inContestAttempts": 3,
        "contestRegistrants": 957
      },
      {
        "name": "Gellyfish and Lycoris Radiata (Hard Version)",
        "tags": ["data structures"],
        "index": "F2",
        "cfRating": 3500,
        "contestId": 2115,
        "clistRating": 4599,
        "problemDate": "2025-05-31T00:00:00",
        "totalAccepted": 47,
        "inContestAccepted": 0,
        "inContestAttempts": 3,
        "contestRegistrants": 957
      },
      {
        "name": "Eastern Exhibition",
        "tags": ["binary search", "geometry", "shortest paths", "sortings"],
        "index": "B",
        "cfRating": 1500,
        "contestId": 1486,
        "clistRating": 1466,
        "problemDate": "2021-02-18T00:00:00",
        "totalAccepted": 17778,
        "inContestAccepted": 4219,
        "inContestAttempts": 6370,
        "contestRegistrants": 13606
      },
      {
        "name": "Circle Game",
        "tags": ["games", "geometry", "math"],
        "index": "D",
        "cfRating": 1700,
        "contestId": 1451,
        "clistRating": 1638,
        "problemDate": "2020-11-21T00:00:00",
        "totalAccepted": 9854,
        "inContestAccepted": 2447,
        "inContestAttempts": 3367,
        "contestRegistrants": 12024
      },
      {
        "name": "Coloring Game",
        "tags": ["binary search", "brute force", "greedy", "two pointers"],
        "index": "C",
        "cfRating": 1300,
        "contestId": 2112,
        "clistRating": 1244,
        "problemDate": "2025-06-23T00:00:00",
        "totalAccepted": 13297,
        "inContestAccepted": 7839,
        "inContestAttempts": 10614,
        "contestRegistrants": 18684
      },
      {
        "name": "Reachability and Tree",
        "tags": ["constructive algorithms", "dfs and similar", "graphs", "trees"],
        "index": "D",
        "cfRating": 1700,
        "contestId": 2112,
        "clistRating": 1701,
        "problemDate": "2025-06-23T00:00:00",
        "totalAccepted": 6739,
        "inContestAccepted": 2615,
        "inContestAttempts": 4966,
        "contestRegistrants": 18684
      },
      {
        "name": "Variables and Operations",
        "tags": ["graphs", "greedy", "shortest paths"],
        "index": "F",
        "cfRating": 2800,
        "contestId": 2112,
        "clistRating": 2764,
        "problemDate": "2025-06-23T00:00:00",
        "totalAccepted": 390,
        "inContestAccepted": 59,
        "inContestAttempts": 291,
        "contestRegistrants": 18684
      },
      {
        "name": "Shashliks",
        "tags": ["greedy", "math"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2113,
        "clistRating": 615,
        "problemDate": "2025-06-15T00:00:00",
        "totalAccepted": 16558,
        "inContestAccepted": 10033,
        "inContestAttempts": 11273,
        "contestRegistrants": 11436
      },
      {
        "name": "Good Start",
        "tags": ["constructive algorithms", "math"],
        "index": "B",
        "cfRating": 1200,
        "contestId": 2113,
        "clistRating": 1174,
        "problemDate": "2025-06-15T00:00:00",
        "totalAccepted": 10840,
        "inContestAccepted": 5696,
        "inContestAttempts": 7308,
        "contestRegistrants": 11436
      },
      {
        "name": "Smilo and Minecraft",
        "tags": ["brute force", "constructive algorithms", "greedy"],
        "index": "C",
        "cfRating": 1700,
        "contestId": 2113,
        "clistRating": 1600,
        "problemDate": "2025-06-15T00:00:00",
        "totalAccepted": 5853,
        "inContestAccepted": 2304,
        "inContestAttempts": 3566,
        "contestRegistrants": 11436
      },
      {
        "name": "Cheater",
        "tags": [
          "binary search",
          "constructive algorithms",
          "greedy",
          "implementation"
        ],
        "index": "D",
        "cfRating": 2200,
        "contestId": 2113,
        "clistRating": 2189,
        "problemDate": "2025-06-15T00:00:00",
        "totalAccepted": 1951,
        "inContestAccepted": 345,
        "inContestAttempts": 1202,
        "contestRegistrants": 11436
      },
      {
        "name": "Two Arrays",
        "tags": ["constructive algorithms", "dfs and similar", "graphs", "math"],
        "index": "F",
        "cfRating": 2500,
        "contestId": 2113,
        "clistRating": 2578,
        "problemDate": "2025-06-15T00:00:00",
        "totalAccepted": 580,
        "inContestAccepted": 90,
        "inContestAttempts": 628,
        "contestRegistrants": 11436
      },
      {
        "name": "From Kazan with Love",
        "tags": ["dfs and similar", "graphs", "implementation", "trees"],
        "index": "E",
        "cfRating": 2800,
        "contestId": 2113,
        "clistRating": 2961,
        "problemDate": "2025-06-15T00:00:00",
        "totalAccepted": 243,
        "inContestAccepted": 19,
        "inContestAttempts": 202,
        "contestRegistrants": 11436
      },
      {
        "name": "Energy Crystals",
        "tags": ["greedy", "implementation", "math"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2111,
        "clistRating": 705,
        "problemDate": "2025-06-03T00:00:00",
        "totalAccepted": 18268,
        "inContestAccepted": 11463,
        "inContestAttempts": 12751,
        "contestRegistrants": 13546
      },
      {
        "name": "Equal Values",
        "tags": ["brute force", "greedy", "two pointers"],
        "index": "C",
        "cfRating": 1100,
        "contestId": 2111,
        "clistRating": 1053,
        "problemDate": "2025-06-03T00:00:00",
        "totalAccepted": 15644,
        "inContestAccepted": 8279,
        "inContestAttempts": 10681,
        "contestRegistrants": 13546
      },
      {
        "name": "Fibonacci Cubes",
        "tags": ["brute force", "dp", "implementation", "math"],
        "index": "B",
        "cfRating": 1100,
        "contestId": 2111,
        "clistRating": 1064,
        "problemDate": "2025-06-03T00:00:00",
        "totalAccepted": 14758,
        "inContestAccepted": 8328,
        "inContestAttempts": 9634,
        "contestRegistrants": 13546
      },
      {
        "name": "Changing the String",
        "tags": [
          "binary search",
          "data structures",
          "greedy",
          "implementation",
          "sortings",
          "strings"
        ],
        "index": "E",
        "cfRating": 1900,
        "contestId": 2111,
        "clistRating": 1943,
        "problemDate": "2025-06-03T00:00:00",
        "totalAccepted": 4242,
        "inContestAccepted": 1077,
        "inContestAttempts": 2590,
        "contestRegistrants": 13546
      },
      {
        "name": "Puzzle",
        "tags": ["brute force", "constructive algorithms", "greedy", "math"],
        "index": "F",
        "cfRating": 2400,
        "contestId": 2111,
        "clistRating": 2413,
        "problemDate": "2025-06-03T00:00:00",
        "totalAccepted": 1092,
        "inContestAccepted": 201,
        "inContestAttempts": 495,
        "contestRegistrants": 13546
      },
      {
        "name": "Divisible Subarrays",
        "tags": [
          "binary search",
          "bitmasks",
          "brute force",
          "data structures",
          "interactive"
        ],
        "index": "G",
        "cfRating": 2900,
        "contestId": 2111,
        "clistRating": 3014,
        "problemDate": "2025-06-03T00:00:00",
        "totalAccepted": 251,
        "inContestAccepted": 20,
        "inContestAttempts": 154,
        "contestRegistrants": 13546
      },
      {
        "name": "Gellyfish and Flaming Peony",
        "tags": ["constructive algorithms", "dp", "math", "number theory"],
        "index": "A",
        "cfRating": 1500,
        "contestId": 2115,
        "clistRating": 1453,
        "problemDate": "2025-05-31T00:00:00",
        "totalAccepted": 10851,
        "inContestAccepted": 5512,
        "inContestAttempts": 8844,
        "contestRegistrants": 19719
      },
      {
        "name": "Gellyfish and Camellia Japonica",
        "tags": [
          "brute force",
          "constructive algorithms",
          "dfs and similar",
          "dp",
          "graphs",
          "greedy",
          "trees"
        ],
        "index": "B",
        "cfRating": 2100,
        "contestId": 2115,
        "clistRating": 2161,
        "problemDate": "2025-05-31T00:00:00",
        "totalAccepted": 2807,
        "inContestAccepted": 846,
        "inContestAttempts": 2197,
        "contestRegistrants": 19719
      },
      {
        "name": "Gellyfish and Eternal Violet",
        "tags": ["combinatorics", "dp", "greedy", "math", "probabilities"],
        "index": "C",
        "cfRating": 2700,
        "contestId": 2115,
        "clistRating": 2764,
        "problemDate": "2025-05-31T00:00:00",
        "totalAccepted": 594,
        "inContestAccepted": 125,
        "inContestAttempts": 449,
        "contestRegistrants": 19719
      },
      {
        "name": "Gellyfish and Forget-Me-Not",
        "tags": ["bitmasks", "dp", "games", "greedy", "math"],
        "index": "D",
        "cfRating": 2900,
        "contestId": 2115,
        "clistRating": 2898,
        "problemDate": "2025-05-31T00:00:00",
        "totalAccepted": 511,
        "inContestAccepted": 83,
        "inContestAttempts": 308,
        "contestRegistrants": 19719
      },
      {
        "name": "Square Year",
        "tags": ["binary search", "brute force", "math"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2114,
        "clistRating": 543,
        "problemDate": "2025-05-26T00:00:00",
        "totalAccepted": 35066,
        "inContestAccepted": 21774,
        "inContestAttempts": 24432,
        "contestRegistrants": 25117
      },
      {
        "name": "Not Quite a Palindromic String",
        "tags": ["greedy", "math"],
        "index": "B",
        "cfRating": 900,
        "contestId": 2114,
        "clistRating": 889,
        "problemDate": "2025-05-26T00:00:00",
        "totalAccepted": 25273,
        "inContestAccepted": 15507,
        "inContestAttempts": 20139,
        "contestRegistrants": 25117
      },
      {
        "name": "Need More Arrays",
        "tags": ["dp", "greedy"],
        "index": "C",
        "cfRating": 1000,
        "contestId": 2114,
        "clistRating": 899,
        "problemDate": "2025-05-26T00:00:00",
        "totalAccepted": 25162,
        "inContestAccepted": 15271,
        "inContestAttempts": 17465,
        "contestRegistrants": 25117
      },
      {
        "name": "Come a Little Closer",
        "tags": ["brute force", "greedy", "implementation", "math"],
        "index": "D",
        "cfRating": 1400,
        "contestId": 2114,
        "clistRating": 1416,
        "problemDate": "2025-05-26T00:00:00",
        "totalAccepted": 11756,
        "inContestAccepted": 5358,
        "inContestAttempts": 8686,
        "contestRegistrants": 25117
      },
      {
        "name": "Small Operations",
        "tags": [
          "binary search",
          "brute force",
          "dfs and similar",
          "dp",
          "math",
          "number theory",
          "sortings"
        ],
        "index": "F",
        "cfRating": 2000,
        "contestId": 2114,
        "clistRating": 2040,
        "problemDate": "2025-05-26T00:00:00",
        "totalAccepted": 4044,
        "inContestAccepted": 697,
        "inContestAttempts": 2694,
        "contestRegistrants": 25117
      },
      {
        "name": "Build an Array",
        "tags": [
          "brute force",
          "constructive algorithms",
          "dp",
          "greedy",
          "math",
          "number theory"
        ],
        "index": "G",
        "cfRating": 2200,
        "contestId": 2114,
        "clistRating": 2404,
        "problemDate": "2025-05-26T00:00:00",
        "totalAccepted": 1501,
        "inContestAccepted": 164,
        "inContestAttempts": 704,
        "contestRegistrants": 25117
      },
      {
        "name": "Fashionable Array",
        "tags": ["implementation", "sortings"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2110,
        "clistRating": 507,
        "problemDate": "2025-05-24T00:00:00",
        "totalAccepted": 25346,
        "inContestAccepted": 16268,
        "inContestAttempts": 17729,
        "contestRegistrants": 18106
      },
      {
        "name": "Down with Brackets",
        "tags": ["strings"],
        "index": "B",
        "cfRating": 900,
        "contestId": 2110,
        "clistRating": 795,
        "problemDate": "2025-05-24T00:00:00",
        "totalAccepted": 21820,
        "inContestAccepted": 13083,
        "inContestAttempts": 15240,
        "contestRegistrants": 18106
      },
      {
        "name": "Racing",
        "tags": ["constructive algorithms", "greedy"],
        "index": "C",
        "cfRating": 1400,
        "contestId": 2110,
        "clistRating": 1327,
        "problemDate": "2025-05-24T00:00:00",
        "totalAccepted": 12483,
        "inContestAccepted": 6434,
        "inContestAttempts": 9400,
        "contestRegistrants": 18106
      },
      {
        "name": "Fewer Batteries",
        "tags": [
          "binary search",
          "dfs and similar",
          "dp",
          "graphs",
          "greedy",
          "hashing"
        ],
        "index": "D",
        "cfRating": 1700,
        "contestId": 2110,
        "clistRating": 1720,
        "problemDate": "2025-05-24T00:00:00",
        "totalAccepted": 6402,
        "inContestAccepted": 2350,
        "inContestAttempts": 3748,
        "contestRegistrants": 18106
      },
      {
        "name": "Melody",
        "tags": ["dfs and similar", "graphs", "implementation"],
        "index": "E",
        "cfRating": 2300,
        "contestId": 2110,
        "clistRating": 2241,
        "problemDate": "2025-05-24T00:00:00",
        "totalAccepted": 1662,
        "inContestAccepted": 416,
        "inContestAttempts": 1022,
        "contestRegistrants": 18106
      },
      {
        "name": "Faculty",
        "tags": ["brute force", "greedy", "math", "number theory"],
        "index": "F",
        "cfRating": 2400,
        "contestId": 2110,
        "clistRating": 2532,
        "problemDate": "2025-05-24T00:00:00",
        "totalAccepted": 1349,
        "inContestAccepted": 137,
        "inContestAttempts": 793,
        "contestRegistrants": 18106
      },
      {
        "name": "It's Time To Duel",
        "tags": ["implementation"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2109,
        "clistRating": 560,
        "problemDate": "2025-05-17T00:00:00",
        "totalAccepted": 23505,
        "inContestAccepted": 14116,
        "inContestAttempts": 16185,
        "contestRegistrants": 16390
      },
      {
        "name": "Hacking Numbers (Easy Version)",
        "tags": [
          "bitmasks",
          "constructive algorithms",
          "interactive",
          "math",
          "number theory"
        ],
        "index": "C1",
        "cfRating": 1500,
        "contestId": 2109,
        "clistRating": 1489,
        "problemDate": "2025-05-17T00:00:00",
        "totalAccepted": 9120,
        "inContestAccepted": 3878,
        "inContestAttempts": 5978,
        "contestRegistrants": 16390
      },
      {
        "name": "Hacking Numbers (Medium Version)",
        "tags": ["constructive algorithms", "interactive", "math", "number theory"],
        "index": "C2",
        "cfRating": 1700,
        "contestId": 2109,
        "clistRating": 1723,
        "problemDate": "2025-05-17T00:00:00",
        "totalAccepted": 6949,
        "inContestAccepted": 2096,
        "inContestAttempts": 2478,
        "contestRegistrants": 16390
      },
      {
        "name": "D/D/D",
        "tags": ["dfs and similar", "graphs", "greedy", "shortest paths"],
        "index": "D",
        "cfRating": 1900,
        "contestId": 2109,
        "clistRating": 1951,
        "problemDate": "2025-05-17T00:00:00",
        "totalAccepted": 4017,
        "inContestAccepted": 1017,
        "inContestAttempts": 1808,
        "contestRegistrants": 16390
      },
      {
        "name": "Binary String Wowee",
        "tags": ["combinatorics", "dp", "strings"],
        "index": "E",
        "cfRating": 2400,
        "contestId": 2109,
        "clistRating": 2428,
        "problemDate": "2025-05-17T00:00:00",
        "totalAccepted": 1055,
        "inContestAccepted": 201,
        "inContestAttempts": 401,
        "contestRegistrants": 16390
      },
      {
        "name": "Penguin Steps",
        "tags": [
          "binary search",
          "dfs and similar",
          "flows",
          "graphs",
          "shortest paths"
        ],
        "index": "F",
        "cfRating": 3000,
        "contestId": 2109,
        "clistRating": 3210,
        "problemDate": "2025-05-17T00:00:00",
        "totalAccepted": 192,
        "inContestAccepted": 12,
        "inContestAttempts": 130,
        "contestRegistrants": 16390
      },
      {
        "name": "Cycling (Easy Version)",
        "tags": ["binary search", "brute force", "dp", "greedy"],
        "index": "F1",
        "cfRating": 2300,
        "contestId": 2107,
        "clistRating": 2315,
        "problemDate": "2025-05-05T00:00:00",
        "totalAccepted": 1416,
        "inContestAccepted": 276,
        "inContestAttempts": 946,
        "contestRegistrants": 12229
      },
      {
        "name": "Cycling (Hard Version)",
        "tags": ["binary search", "brute force", "data structures", "dp", "greedy"],
        "index": "F2",
        "cfRating": 2800,
        "contestId": 2107,
        "clistRating": 2862,
        "problemDate": "2025-05-05T00:00:00",
        "totalAccepted": 327,
        "inContestAccepted": 34,
        "inContestAttempts": 129,
        "contestRegistrants": 12229
      },
      {
        "name": "Permutation Warm-Up",
        "tags": ["combinatorics", "greedy", "math"],
        "index": "A",
        "cfRating": 800,
        "contestId": 2108,
        "clistRating": 462,
        "problemDate": "2025-05-01T00:00:00",
        "totalAccepted": 19487,
        "inContestAccepted": 10576,
        "inContestAttempts": 11117,
        "contestRegistrants": 11433
      },
      {
        "name": "SUMdamental Decomposition",
        "tags": [
          "bitmasks",
          "constructive algorithms",
          "greedy",
          "implementation",
          "math"
        ],
        "index": "B",
        "cfRating": 1300,
        "contestId": 2108,
        "clistRating": 1291,
        "problemDate": "2025-05-01T00:00:00",
        "totalAccepted": 12172,
        "inContestAccepted": 4814,
        "inContestAttempts": 6664,
        "contestRegistrants": 11433
      },
      {
        "name": "Neo's Escape",
        "tags": [
          "binary search",
          "brute force",
          "data structures",
          "dp",
          "dsu",
          "graphs",
          "greedy",
          "implementation"
        ],
        "index": "C",
        "cfRating": 1500,
        "contestId": 2108,
        "clistRating": 1405,
        "problemDate": "2025-05-01T00:00:00",
        "totalAccepted": 11487,
        "inContestAccepted": 3983,
        "inContestAttempts": 5700,
        "contestRegistrants": 11433
      },
      {
        "name": "Needle in a Numstack",
        "tags": ["binary search", "brute force", "implementation", "interactive"],
        "index": "D",
        "cfRating": 2200,
        "contestId": 2108,
        "clistRating": 2206,
        "problemDate": "2025-05-01T00:00:00",
        "totalAccepted": 1990,
        "inContestAccepted": 412,
        "inContestAttempts": 1749,
        "contestRegistrants": 11433
      },
      {
        "name": "Fallen Towers",
        "tags": ["binary search", "greedy"],
        "index": "F",
        "cfRating": 2900,
        "contestId": 2108,
        "clistRating": 3097,
        "problemDate": "2025-05-01T00:00:00",
        "totalAccepted": 383,
        "inContestAccepted": 16,
        "inContestAttempts": 105,
        "contestRegistrants": 11433
      },
      {
        "name": "Max Median",
        "tags": ["binary search", "data structures", "dp"],
        "index": "D",
        "cfRating": 2100,
        "contestId": 1486,
        "clistRating": 2160,
        "problemDate": "2021-02-18T00:00:00",
        "totalAccepted": 8426,
        "inContestAccepted": 646,
        "inContestAttempts": 2230,
        "contestRegistrants": 13606
      },
      {
        "name": "Mex in the Grid",
        "tags": ["constructive algorithms", "implementation"],
        "index": "A",
        "cfRating": 1300,
        "contestId": 2101,
        "clistRating": 1290,
        "problemDate": "2025-05-11T00:00:00",
        "totalAccepted": 11371,
        "inContestAccepted": 5375,
        "inContestAttempts": 7749,
        "contestRegistrants": 12288
      },
      {
        "name": "Quartet Swapping",
        "tags": [
          "brute force",
          "data structures",
          "divide and conquer",
          "greedy",
          "sortings"
        ],
        "index": "B",
        "cfRating": 1800,
        "contestId": 2101,
        "clistRating": 1780,
        "problemDate": "2025-05-11T00:00:00",
        "totalAccepted": 5498,
        "inContestAccepted": 1967,
        "inContestAttempts": 5144,
        "contestRegistrants": 12288
      }
    ];
  },

  getProductsWithOrdersData() {
    return [
      {
        id: "1000",
        code: "f230fh0g3",
        name: "Bamboo Watch",
        description: "Product Description",
        image: "bamboo-watch.jpg",
        price: 65,
        category: "Accessories",
        quantity: 24,
        inventoryStatus: "INSTOCK",
        rating: 5,
        orders: [
          {
            id: "1000-0",
            productCode: "f230fh0g3",
            date: "2020-09-13",
            amount: 65,
            quantity: 1,
            customer: "David James",
            status: "PENDING",
          },
          {
            id: "1000-1",
            productCode: "f230fh0g3",
            date: "2020-05-14",
            amount: 130,
            quantity: 2,
            customer: "Leon Rodrigues",
            status: "DELIVERED",
          },
          {
            id: "1000-2",
            productCode: "f230fh0g3",
            date: "2019-01-04",
            amount: 65,
            quantity: 1,
            customer: "Juan Alejandro",
            status: "RETURNED",
          },
          {
            id: "1000-3",
            productCode: "f230fh0g3",
            date: "2020-09-13",
            amount: 195,
            quantity: 3,
            customer: "Claire Morrow",
            status: "CANCELLED",
          },
        ],
      },
      {
        id: "1001",
        code: "nvklal433",
        name: "Black Watch",
        description: "Product Description",
        image: "black-watch.jpg",
        price: 72,
        category: "Accessories",
        quantity: 61,
        inventoryStatus: "INSTOCK",
        rating: 4,
        orders: [
          {
            id: "1001-0",
            productCode: "nvklal433",
            date: "2020-05-14",
            amount: 72,
            quantity: 1,
            customer: "Maisha Jefferson",
            status: "DELIVERED",
          },
          {
            id: "1001-1",
            productCode: "nvklal433",
            date: "2020-02-28",
            amount: 144,
            quantity: 2,
            customer: "Octavia Murillo",
            status: "PENDING",
          },
        ],
      },
      {
        id: "1002",
        code: "zz21cz3c1",
        name: "Blue Band",
        description: "Product Description",
        image: "blue-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 2,
        inventoryStatus: "LOWSTOCK",
        rating: 3,
        orders: [
          {
            id: "1002-0",
            productCode: "zz21cz3c1",
            date: "2020-07-05",
            amount: 79,
            quantity: 1,
            customer: "Stacey Leja",
            status: "DELIVERED",
          },
          {
            id: "1002-1",
            productCode: "zz21cz3c1",
            date: "2020-02-06",
            amount: 79,
            quantity: 1,
            customer: "Ashley Wickens",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1003",
        code: "244wgerg2",
        name: "Blue T-Shirt",
        description: "Product Description",
        image: "blue-t-shirt.jpg",
        price: 29,
        category: "Clothing",
        quantity: 25,
        inventoryStatus: "INSTOCK",
        rating: 5,
        orders: [],
      },
      {
        id: "1004",
        code: "h456wer53",
        name: "Bracelet",
        description: "Product Description",
        image: "bracelet.jpg",
        price: 15,
        category: "Accessories",
        quantity: 73,
        inventoryStatus: "INSTOCK",
        rating: 4,
        orders: [
          {
            id: "1004-0",
            productCode: "h456wer53",
            date: "2020-09-05",
            amount: 60,
            quantity: 4,
            customer: "Mayumi Misaki",
            status: "PENDING",
          },
          {
            id: "1004-1",
            productCode: "h456wer53",
            date: "2019-04-16",
            amount: 2,
            quantity: 30,
            customer: "Francesco Salvatore",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1005",
        code: "av2231fwg",
        name: "Brown Purse",
        description: "Product Description",
        image: "brown-purse.jpg",
        price: 120,
        category: "Accessories",
        quantity: 0,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
        orders: [
          {
            id: "1005-0",
            productCode: "av2231fwg",
            date: "2020-01-25",
            amount: 120,
            quantity: 1,
            customer: "Isabel Sinclair",
            status: "RETURNED",
          },
          {
            id: "1005-1",
            productCode: "av2231fwg",
            date: "2019-03-12",
            amount: 240,
            quantity: 2,
            customer: "Lionel Clifford",
            status: "DELIVERED",
          },
          {
            id: "1005-2",
            productCode: "av2231fwg",
            date: "2019-05-05",
            amount: 120,
            quantity: 1,
            customer: "Cody Chavez",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1006",
        code: "bib36pfvm",
        name: "Chakra Bracelet",
        description: "Product Description",
        image: "chakra-bracelet.jpg",
        price: 32,
        category: "Accessories",
        quantity: 5,
        inventoryStatus: "LOWSTOCK",
        rating: 3,
        orders: [
          {
            id: "1006-0",
            productCode: "bib36pfvm",
            date: "2020-02-24",
            amount: 32,
            quantity: 1,
            customer: "Arvin Darci",
            status: "DELIVERED",
          },
          {
            id: "1006-1",
            productCode: "bib36pfvm",
            date: "2020-01-14",
            amount: 64,
            quantity: 2,
            customer: "Izzy Jones",
            status: "PENDING",
          },
        ],
      },
      {
        id: "1007",
        code: "mbvjkgip5",
        name: "Galaxy Earrings",
        description: "Product Description",
        image: "galaxy-earrings.jpg",
        price: 34,
        category: "Accessories",
        quantity: 23,
        inventoryStatus: "INSTOCK",
        rating: 5,
        orders: [
          {
            id: "1007-0",
            productCode: "mbvjkgip5",
            date: "2020-06-19",
            amount: 34,
            quantity: 1,
            customer: "Jennifer Smith",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1008",
        code: "vbb124btr",
        name: "Game Controller",
        description: "Product Description",
        image: "game-controller.jpg",
        price: 99,
        category: "Electronics",
        quantity: 2,
        inventoryStatus: "LOWSTOCK",
        rating: 4,
        orders: [
          {
            id: "1008-0",
            productCode: "vbb124btr",
            date: "2020-01-05",
            amount: 99,
            quantity: 1,
            customer: "Jeanfrancois David",
            status: "DELIVERED",
          },
          {
            id: "1008-1",
            productCode: "vbb124btr",
            date: "2020-01-19",
            amount: 198,
            quantity: 2,
            customer: "Ivar Greenwood",
            status: "RETURNED",
          },
        ],
      },
      {
        id: "1009",
        code: "cm230f032",
        name: "Gaming Set",
        description: "Product Description",
        image: "gaming-set.jpg",
        price: 299,
        category: "Electronics",
        quantity: 63,
        inventoryStatus: "INSTOCK",
        rating: 3,
        orders: [
          {
            id: "1009-0",
            productCode: "cm230f032",
            date: "2020-06-24",
            amount: 299,
            quantity: 1,
            customer: "Kadeem Mujtaba",
            status: "PENDING",
          },
          {
            id: "1009-1",
            productCode: "cm230f032",
            date: "2020-05-11",
            amount: 299,
            quantity: 1,
            customer: "Ashley Wickens",
            status: "DELIVERED",
          },
          {
            id: "1009-2",
            productCode: "cm230f032",
            date: "2019-02-07",
            amount: 299,
            quantity: 1,
            customer: "Julie Johnson",
            status: "DELIVERED",
          },
          {
            id: "1009-3",
            productCode: "cm230f032",
            date: "2020-04-26",
            amount: 299,
            quantity: 1,
            customer: "Tony Costa",
            status: "CANCELLED",
          },
        ],
      },
      {
        id: "1010",
        code: "plb34234v",
        name: "Gold Phone Case",
        description: "Product Description",
        image: "gold-phone-case.jpg",
        price: 24,
        category: "Accessories",
        quantity: 0,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
        orders: [
          {
            id: "1010-0",
            productCode: "plb34234v",
            date: "2020-02-04",
            amount: 24,
            quantity: 1,
            customer: "James Butt",
            status: "DELIVERED",
          },
          {
            id: "1010-1",
            productCode: "plb34234v",
            date: "2020-05-05",
            amount: 48,
            quantity: 2,
            customer: "Josephine Darakjy",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1011",
        code: "4920nnc2d",
        name: "Green Earbuds",
        description: "Product Description",
        image: "green-earbuds.jpg",
        price: 89,
        category: "Electronics",
        quantity: 23,
        inventoryStatus: "INSTOCK",
        rating: 4,
        orders: [
          {
            id: "1011-0",
            productCode: "4920nnc2d",
            date: "2020-06-01",
            amount: 89,
            quantity: 1,
            customer: "Art Venere",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1012",
        code: "250vm23cc",
        name: "Green T-Shirt",
        description: "Product Description",
        image: "green-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 74,
        inventoryStatus: "INSTOCK",
        rating: 5,
        orders: [
          {
            id: "1012-0",
            productCode: "250vm23cc",
            date: "2020-02-05",
            amount: 49,
            quantity: 1,
            customer: "Lenna Paprocki",
            status: "DELIVERED",
          },
          {
            id: "1012-1",
            productCode: "250vm23cc",
            date: "2020-02-15",
            amount: 49,
            quantity: 1,
            customer: "Donette Foller",
            status: "PENDING",
          },
        ],
      },
      {
        id: "1013",
        code: "fldsmn31b",
        name: "Grey T-Shirt",
        description: "Product Description",
        image: "grey-t-shirt.jpg",
        price: 48,
        category: "Clothing",
        quantity: 0,
        inventoryStatus: "OUTOFSTOCK",
        rating: 3,
        orders: [
          {
            id: "1013-0",
            productCode: "fldsmn31b",
            date: "2020-04-01",
            amount: 48,
            quantity: 1,
            customer: "Simona Morasca",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1014",
        code: "waas1x2as",
        name: "Headphones",
        description: "Product Description",
        image: "headphones.jpg",
        price: 175,
        category: "Electronics",
        quantity: 8,
        inventoryStatus: "LOWSTOCK",
        rating: 5,
        orders: [
          {
            id: "1014-0",
            productCode: "waas1x2as",
            date: "2020-05-15",
            amount: 175,
            quantity: 1,
            customer: "Lenna Paprocki",
            status: "DELIVERED",
          },
          {
            id: "1014-1",
            productCode: "waas1x2as",
            date: "2020-01-02",
            amount: 175,
            quantity: 1,
            customer: "Donette Foller",
            status: "CANCELLED",
          },
        ],
      },
      {
        id: "1015",
        code: "vb34btbg5",
        name: "Light Green T-Shirt",
        description: "Product Description",
        image: "light-green-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 34,
        inventoryStatus: "INSTOCK",
        rating: 4,
        orders: [
          {
            id: "1015-0",
            productCode: "vb34btbg5",
            date: "2020-07-02",
            amount: 98,
            quantity: 2,
            customer: "Mitsue Tollner",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1016",
        code: "k8l6j58jl",
        name: "Lime Band",
        description: "Product Description",
        image: "lime-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 12,
        inventoryStatus: "INSTOCK",
        rating: 3,
        orders: [],
      },
      {
        id: "1017",
        code: "v435nn85n",
        name: "Mini Speakers",
        description: "Product Description",
        image: "mini-speakers.jpg",
        price: 85,
        category: "Clothing",
        quantity: 42,
        inventoryStatus: "INSTOCK",
        rating: 4,
        orders: [
          {
            id: "1017-0",
            productCode: "v435nn85n",
            date: "2020-07-12",
            amount: 85,
            quantity: 1,
            customer: "Minna Amigon",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1018",
        code: "09zx9c0zc",
        name: "Painted Phone Case",
        description: "Product Description",
        image: "painted-phone-case.jpg",
        price: 56,
        category: "Accessories",
        quantity: 41,
        inventoryStatus: "INSTOCK",
        rating: 5,
        orders: [
          {
            id: "1018-0",
            productCode: "09zx9c0zc",
            date: "2020-07-01",
            amount: 56,
            quantity: 1,
            customer: "Abel Maclead",
            status: "DELIVERED",
          },
          {
            id: "1018-1",
            productCode: "09zx9c0zc",
            date: "2020-05-02",
            amount: 56,
            quantity: 1,
            customer: "Minna Amigon",
            status: "RETURNED",
          },
        ],
      },
      {
        id: "1019",
        code: "mnb5mb2m5",
        name: "Pink Band",
        description: "Product Description",
        image: "pink-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 63,
        inventoryStatus: "INSTOCK",
        rating: 4,
        orders: [],
      },
      {
        id: "1020",
        code: "r23fwf2w3",
        name: "Pink Purse",
        description: "Product Description",
        image: "pink-purse.jpg",
        price: 110,
        category: "Accessories",
        quantity: 0,
        inventoryStatus: "OUTOFSTOCK",
        rating: 4,
        orders: [
          {
            id: "1020-0",
            productCode: "r23fwf2w3",
            date: "2020-05-29",
            amount: 110,
            quantity: 1,
            customer: "Kiley Caldarera",
            status: "DELIVERED",
          },
          {
            id: "1020-1",
            productCode: "r23fwf2w3",
            date: "2020-02-11",
            amount: 220,
            quantity: 2,
            customer: "Graciela Ruta",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1021",
        code: "pxpzczo23",
        name: "Purple Band",
        description: "Product Description",
        image: "purple-band.jpg",
        price: 79,
        category: "Fitness",
        quantity: 6,
        inventoryStatus: "LOWSTOCK",
        rating: 3,
        orders: [
          {
            id: "1021-0",
            productCode: "pxpzczo23",
            date: "2020-02-02",
            amount: 79,
            quantity: 1,
            customer: "Cammy Albares",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1022",
        code: "2c42cb5cb",
        name: "Purple Gemstone Necklace",
        description: "Product Description",
        image: "purple-gemstone-necklace.jpg",
        price: 45,
        category: "Accessories",
        quantity: 62,
        inventoryStatus: "INSTOCK",
        rating: 4,
        orders: [
          {
            id: "1022-0",
            productCode: "2c42cb5cb",
            date: "2020-06-29",
            amount: 45,
            quantity: 1,
            customer: "Mattie Poquette",
            status: "DELIVERED",
          },
          {
            id: "1022-1",
            productCode: "2c42cb5cb",
            date: "2020-02-11",
            amount: 135,
            quantity: 3,
            customer: "Meaghan Garufi",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1023",
        code: "5k43kkk23",
        name: "Purple T-Shirt",
        description: "Product Description",
        image: "purple-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 2,
        inventoryStatus: "LOWSTOCK",
        rating: 5,
        orders: [
          {
            id: "1023-0",
            productCode: "5k43kkk23",
            date: "2020-04-15",
            amount: 49,
            quantity: 1,
            customer: "Gladys Rim",
            status: "RETURNED",
          },
        ],
      },
      {
        id: "1024",
        code: "lm2tny2k4",
        name: "Shoes",
        description: "Product Description",
        image: "shoes.jpg",
        price: 64,
        category: "Clothing",
        quantity: 0,
        inventoryStatus: "INSTOCK",
        rating: 4,
        orders: [],
      },
      {
        id: "1025",
        code: "nbm5mv45n",
        name: "Sneakers",
        description: "Product Description",
        image: "sneakers.jpg",
        price: 78,
        category: "Clothing",
        quantity: 52,
        inventoryStatus: "INSTOCK",
        rating: 4,
        orders: [
          {
            id: "1025-0",
            productCode: "nbm5mv45n",
            date: "2020-02-19",
            amount: 78,
            quantity: 1,
            customer: "Yuki Whobrey",
            status: "DELIVERED",
          },
          {
            id: "1025-1",
            productCode: "nbm5mv45n",
            date: "2020-05-21",
            amount: 78,
            quantity: 1,
            customer: "Fletcher Flosi",
            status: "PENDING",
          },
        ],
      },
      {
        id: "1026",
        code: "zx23zc42c",
        name: "Teal T-Shirt",
        description: "Product Description",
        image: "teal-t-shirt.jpg",
        price: 49,
        category: "Clothing",
        quantity: 3,
        inventoryStatus: "LOWSTOCK",
        rating: 3,
        orders: [
          {
            id: "1026-0",
            productCode: "zx23zc42c",
            date: "2020-04-24",
            amount: 98,
            quantity: 2,
            customer: "Bette Nicka",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1027",
        code: "acvx872gc",
        name: "Yellow Earbuds",
        description: "Product Description",
        image: "yellow-earbuds.jpg",
        price: 89,
        category: "Electronics",
        quantity: 35,
        inventoryStatus: "INSTOCK",
        rating: 3,
        orders: [
          {
            id: "1027-0",
            productCode: "acvx872gc",
            date: "2020-01-29",
            amount: 89,
            quantity: 1,
            customer: "Veronika Inouye",
            status: "DELIVERED",
          },
          {
            id: "1027-1",
            productCode: "acvx872gc",
            date: "2020-06-11",
            amount: 89,
            quantity: 1,
            customer: "Willard Kolmetz",
            status: "DELIVERED",
          },
        ],
      },
      {
        id: "1028",
        code: "tx125ck42",
        name: "Yoga Mat",
        description: "Product Description",
        image: "yoga-mat.jpg",
        price: 20,
        category: "Fitness",
        quantity: 15,
        inventoryStatus: "INSTOCK",
        rating: 5,
        orders: [],
      },
      {
        id: "1029",
        code: "gwuby345v",
        name: "Yoga Set",
        description: "Product Description",
        image: "yoga-set.jpg",
        price: 20,
        category: "Fitness",
        quantity: 25,
        inventoryStatus: "INSTOCK",
        rating: 8,
        orders: [
          {
            id: "1029-0",
            productCode: "gwuby345v",
            date: "2020-02-14",
            amount: 4,
            quantity: 80,
            customer: "Maryann Royster",
            status: "DELIVERED",
          },
        ],
      },
    ];
  },
  getProblemsMini(): Promise<Problem[]> {
    return Promise.resolve(this.getProblemsData().slice(0, 5));
  },

  getProblemsSmall(): Promise<Problem[]> {
    return Promise.resolve(this.getProblemsData().slice(0, 10));
  },

  getProblems(): Promise<Problem[]> {
    return Promise.resolve(this.getProblemsData());
  },

  getProblemsWithOrdersSmall(): Promise<Problem[]> {
    return Promise.resolve(this.getProblemsWithOrdersData().slice(0, 10));
  },

  getProblemsWithOrders(): Promise<Problem[]> {
    return Promise.resolve(this.getProblemsWithOrdersData());
  },

  getProblemsWithOrdersData(): Problem[] {
    // TODO: Return actual problem data with orders
    return [];
  }

};
